sudo: false
language: ruby
cache: bundler
script: bundle exec rspec

rvm:
  - 2.5

before_install:
  - npm install -g mjml

env:
  matrix:
    - RAILS_VERSION=5
    - RAILS_VERSION=master

matrix:
  fast_finish: true
  allow_failures:
    - env: RAILS_VERSION=master
